---
- name: Uninstall and start the apche
  hosts: all 
  become: yes

  tasks: 
  - name: Stop the servive
    service:
        name=httpd
        state=stopped

  - name: Uninstall the http 
    yum: 
      name=httpd
      state=absent


